#!/bin/bash
#
# This will run commands inside of the chroot enviroment 
#

if [[ -d ${COMMANDS_DIR} ]];then

  for file in $(ls ${COMMANDS_DIR}); do

    set_ifs $'\n'

    for cmd in $(cat ${COMMANDS_DIR}/${file} | grep -v '^$\|^\s*\#'); do
      run_chroot_command ${CHROOT_DIR} "${cmd}"

    done
	
    return_ifs
  
  done

fi
